### ISSUE TITLE
ImportError from distribute_setup.py, line 143

### ISSUE THREAD

**Issue by diamond-lizard** [zacharyvoase/jsonpipe#7]
When trying to `"pip3.6 install --user jsonpipe"` I get this error:

```
%  pip3.6 install --user jsonpipe
Collecting jsonpipe
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/47/e6/c635a9ce1769559167bb04e1106c4b22223084005d440472e5ead1d6b346/jsonpipe-0.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Traceback (most recent call last):
      File "/home/me/tmp/pip-build-sfedaf0j/jsonpipe/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/me/tmp/pip-build-sfedaf0j/jsonpipe/setup.py", line 5, in <module>
        use_setuptools()
      File "/home/me/tmp/pip-build-sfedaf0j/jsonpipe/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/home/me/tmp/pip-build-sfedaf0j/jsonpipe/distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "/home/me/tmp/pip-build-sfedaf0j/jsonpipe/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/cthulhu/tmp/pip-build-sfedaf0j/jsonpipe/
```

**Comment by twogood** [comment]
Never mind, this will just open a new can of worms because `distribute` is deprecated, etc...
